name: Run RSpec tests
on: [push]
jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        # ruby version is read from .tool-versions file, do not specify here
        bundler-cache: true
    - name: Run tests
      run: bundle exec rspec
